### ISSUE TITLE
Custom commnad `jet_custom_apps_example` broken in django 1.10

### ISSUE THREAD

**Issue by SalahAdDin** [JensAstrup/django-jetpack#7]
Testing `django 1.10` i get this error:

![seleccion_105](https://cloud.githubusercontent.com/assets/5034215/16183038/5dbbed90-3672-11e6-8ae6-4e8273a75d39.png)

```bash
 salahaddin@TulipanROG  ~/Proyectos/tiempoturco/tiempoturco  (tiempoturco)  ./manage.py  jet_custom_apps_example                                                                                                                             ✓  636  23:03:19 
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/tiempoturco/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/tiempoturco/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/salahaddin/Proyectos/tiempoturco/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/salahaddin/Proyectos/tiempoturco/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/salahaddin/Proyectos/tiempoturco/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/tiempoturco/lib/python3.5/site-packages/jet/management/commands/jet_custom_apps_example.py", line 1, in <module>
    from django.core.management.base import NoArgsCommand
ImportError: cannot import name 'NoArgsCommand'

```

These class isn't in `django 1.10`.

**Comment by SalahAdDin** [comment]
Ok, will solve changing `NoArgsCommand`by `BaseCommand`.

**Comment by SalahAdDin** [comment]
Solved.
